// Test.idl: Test 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(Test.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(c255a35d-567b-4c61-b395-c2dba61a086b),
	version(1.0),
]
library TestLib
{
	importlib("stdole2.tlb");
};

